### ISSUE TITLE
Getting this crash

### ISSUE THREAD

**Issue by iZakirSheikh** [GIGAMOLE/ComposeFadingEdges#4]
```
   	at androidx.compose.ui.platform.GraphicsLayerOwnerLayer.drawLayer(GraphicsLayerOwnerLayer.android.kt:236)
                 	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:429)
                 	at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:972)
                 	at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:177)
                 	at androidx.compose.ui.node.LayoutNodeDrawScope.drawContent(LayoutNodeDrawScope.kt:63)
14:49:50.762  E  	at androidx.compose.foundation.StretchOverscrollNode.draw(AndroidOverscroll.android.kt:244) (Ask Gemini)
                 	at androidx.compose.ui.node.LayoutNodeDrawScope.drawDirect-eZhPAX0$ui_release(LayoutNodeDrawScope.kt:96)
                 	at androidx.compose.ui.node.LayoutNodeDrawScope.draw-eZhPAX0$ui_release(LayoutNodeDrawScope.kt:83)
                 	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:445)
                 	at androidx.compose.ui.node.NodeCoordinator.access$drawContainedDrawModifiers(NodeCoordinator.kt:63)
                 	at androidx.compose.ui.node.NodeCoordinator$drawBlock$drawBlockCallToDrawModifiers$1.invoke(NodeCoordinator.kt:468)
                 	at androidx.compose.ui.node.NodeCoordinator$drawBlock$drawBlockCallToDrawModifiers$1.invoke(NodeCoordinator.kt:467)
                 	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2489)
                 	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:460)
                 	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:244)
                 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:124)
                 	at androidx.compose.ui.node.NodeCoordinator$drawBlock$1.invoke(NodeCoordinator.kt:474)
                 	at androidx.compose.ui.node.NodeCoordinator$drawBlock$1.invoke(NodeCoordinator.kt:470)
                 	at androidx.compose.ui.platform.GraphicsLayerOwnerLayer$recordLambda$1.invoke(GraphicsLayerOwnerLayer.android.kt:261)
                 	at androidx.compose.ui.platform.GraphicsLayerOwnerLayer$recordLambda$1.invoke(GraphicsLayerOwnerLayer.android.kt:259)
                 	at androidx.compose.ui.graphics.layer.GraphicsLayer$clipDrawBlock$1.invoke(AndroidGraphicsLayer.android.kt:72)
                 	at androidx.compose.ui.graphics.layer.GraphicsLayer$clipDrawBlock$1.invoke(AndroidGraphicsLayer.android.kt:67)
                 	at androidx.compose.ui.graphics.layer.GraphicsLayerV29.record(GraphicsLayerV29.android.kt:251)
                 	at androidx.compose.ui.graphics.layer.GraphicsLayer.recordInternal(AndroidGraphicsLayer.android.kt:438)
                 	at androidx.compose.ui.graphics.layer.GraphicsLayer.record-mL-hObY(AndroidGraphicsLayer.android.kt:431)
                 	at androidx.compose.ui.platform.GraphicsLayerOwnerLayer.updateDisplayList(GraphicsLayerOwnerLayer.android.kt:254)
                 	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(AndroidComposeView.android.kt:1671)
                 	at android.view.View.draw(View.java:23304)
                 	at android.view.View.updateDisplayListIfDirty(View.java:22168)
                 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4525)
                 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4498)
                 	at android.view.View.updateDisplayListIfDirty(View.java:22124)
                 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4525)
                 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4498)
                 	at android.view.View.updateDisplayListIfDirty(View.java:22124)
                 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4525)
                 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4498)
                 	at android.view.View.updateDisplayListIfDirty(View.java:22124)
                 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4525)
                 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4498)
                 	at android.view.View.updateDisplayListIfDirty(View.java:22124)
                 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:689)
                 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:695)
                 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:793)
                 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5064)
                 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4773)
                 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3983)
                 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2580)
                 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9586)
                 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
                 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
14:49:50.762  E  	at android.view.Choreographer.doCallbacks(Choreographer.java:899) (Ask Gemini)
                 	at android.view.Choreographer.doFrame(Choreographer.java:832)
                 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
                 	at android.os.Handler.handleCallback(Handler.java:984)
                 	at android.os.Handler.dispatchMessage(Handler.java:104)
                 	at android.os.Looper.loopOnce(Looper.java:238)
                 	at android.os.Looper.loop(Looper.java:357)
                 	at android.app.ActivityThread.main(ActivityThread.java:8160)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:957)
```

**Comment by GIGAMOLE** [comment]
Hi. Is it reproducible? Please, send me a video or a code fragment. I think it has to do something with the Compose itself, it is clearly coming from the inside.

**Comment by googol-apps** [comment]
> Hi. Is it reproducible? Please, send me a video or a code fragment. I think it has to do something with the Compose itself, it is clearly coming from the inside.

Hello sir. I my salf created a simple fadingEdge modifier to test and I noticed that similar error occurs if we calculate radius.DP.toPx within the scope of GraphicsLayer. If we move the. Caculation within the original ContentDrawSope, it goes away.
Hope this helps.
